### ISSUE TITLE
Grouping rules

### ISSUE THREAD

**Issue by Mottie** [webonise/tablesorter-grouping#1]
I don't quite understand how the rows are being grouped. 

When I open [the demo](http://files.enfranchisedmind.com/tablesorter-grouping/demo.html) it is unsorted and I see a grouped row 18 rows down. I don't understand how this row is grouped.

When I sort the first column, I see three group rows. The point at which the rows are grouped appear arbitrary. I would think that there would be two group headers, one at the top before "Alfalfa" and the second before "Soybeans".

![2014-10-21 13_29_43-files enfranchisedmind com_tablesorter-grouping_demo html](https://cloud.githubusercontent.com/assets/136959/4724580/dff64a12-5951-11e4-9b2f-838baafb186d.png)

I am probably biased in my beliefs, because I wrote a [grouping widget](http://mottie.github.io/tablesorter/docs/example-widget-grouping.html) for my fork of tablesorter which behaves quite differently.

Thanks for your work in creating this widget, and taking the time to read my ramblings.

**Comment by RobertFischer** [comment]
Fixed with Pull Request #2.

**Comment by RobertFischer** [comment]
This commit—added some more help in the README: https://github.com/webonise/tablesorter-grouping/commit/bd7a81a6116723f50bd333c7095aaa4d302edd80

I'm not sure what you find as "arbitrary" about the groupings. If the values of the key columns match the previous row, then the rows are grouped. There are three key columns in the demo, not one, so it has to match all three leftmost columns in order for two rows to be grouped.

Note that in the case of the demo, the first three columns are all key columns, so it has to match all three. An earlier iteration of this library allowed "partial matches", but that was more visually confusing than helpful. It would be easy to extend to enable partial matches, if you'd like.
